### ISSUE TITLE
Asisintel Indoor / Sim Issue

### ISSUE THREAD

**Issue by kastnerp** [EnvironmentalSystemsLab/Eddy3D-Public#1]
From Asisintel :
.I installed the updated eddy3d version 0.4.1.0 but still indoor component doesnt run. Outdoors are fine.

![image](https://user-images.githubusercontent.com/1919773/165788677-06635227-3b36-4518-bc10-3ba3307e1240.png)

I am also sharing the example file with updatd eddy component that threw error for you to check.

I think the new component still searching bluecfd 2017 but we have now bluecfd 2020
I managed to take a snap shot while runing batch command

![image](https://user-images.githubusercontent.com/1919773/165788694-69bac0cb-2578-4230-9839-ca5ab1d2cc3d.png)

I have the GH files too, posted here on behalf of him : https://drive.google.com/drive/folders/1b_5sU9TvV88fwpLSUhwkaJojLgoJwWpG?usp=sharing

**Comment by kastnerp** [comment]
@Asisintel I suggest sticking to this test case which was tested with BlueCFD 2020 / OF8. More detailed questions can be answered by @zoedesimone.

![image](https://user-images.githubusercontent.com/1919773/165788912-35b6ace4-cca2-474d-91e8-83756c42c0f9.png)


I think the new component still searching bluecfd 2017 but we have now bluecfd 2020. I managed to take a snap shot while runing batch command

I cannot reproduce this on my end unfortunately.

Best,

Patrick

[IndoorExample.zip](https://github.com/EnvironmentalSystemsLab/Eddy3D-Public/files/8584150/IndoorExample.zip)

**Comment by asisnatha** [comment]
Thanks for testing it ou @kastnerp . Can you pls check the sample you have attched. I think its not the same file as shown by you in the above image. Its the same file I had attached earlier.

**Comment by asisnatha** [comment]
Thanks again. But unfortunately this is also not working. I tried on both of my system and its still not able to run this. Do we need to have both BCFD 2017 and 2020 installed?

**Comment by asisnatha** [comment]
Just an info. I checked the batch file of the example you shared. But as you can see its looking for 2017 version. If I am manually changing it to 2020 version its starting to run but fails as I am runnig externally. So i am preetty sure I am getting error beacuse of OF 2017 look out.
![image](https://user-images.githubusercontent.com/41608759/165827508-486542c6-27b5-45ba-88ec-5b354a56ffd2.png)

**Comment by kastnerp** [comment]
@asisnatha I unfortunately cannot reproduce what you report on my machine. I do not currently have BlueCFD-2017 installed and the test case runs fine for me. I suspect you might be loading a previous version of Eddy3D with Grasshopper or there might be some cache issue with old files lingering around.

**Comment by asisnatha** [comment]
@kastnerp I dont know. But I installed Rhino and eddy3d beta version on a new laptop of my collegue to test it out. Still its unable to ru it. All other coponents are running well with Bcfd 2020 only this component is trying to load 2017 version. Is it an issue with the installer?

**Comment by asisnatha** [comment]
I am on it

**Comment by asisnatha** [comment]
can you please check the link I am unable to downlaod it. It is throwing error

**Comment by kastnerp** [comment]
Just downloaded the installer myself from the website.

**Comment by asisnatha** [comment]
hi again. I tested the above example and I want to highlight one point which I think is creating error for indoor cases when we are providing our own model except the example file. If in the example file share by @kastnerp I remove function object, the simulation fails, while If I attach again it works. So in any individual project is it necessary to provide all function-object as input for the indoor component to work or is it a bug?

**Comment by kastnerp** [comment]
Referencing @zoedesimone who is leading the indoor module effort.

**Comment by asisnatha** [comment]
hi @zoedesimone. Any update on this!

**Comment by zoedesimone** [comment]
Hi @asisnatha, could you please provide the error message you are getting? The simulation should work without function objects.
Thanks,
Zoe

**Comment by asisnatha** [comment]
Hi. thanks for your reply. The simulation runs for some minutes and abruptly stops  when function object is ermoved. It works perectly when function objects are reassigned.
![image](https://user-images.githubusercontent.com/41608759/166116870-c56ef104-ac29-4de3-a7e7-32b92b662c2b.png)

I am sharing the result folder link that is created after this issue occurs, hope this would help in debugging
https://drive.google.com/file/d/1NM4w22nACxsQNExXWS1aDudM9_fUq37x/view?usp=sharing

**Comment by asisnatha** [comment]
I managed to take a snap of the batch file showing fatal error. What I am guessing is even after removing thefunction objects its seeking the data for function objects. even I drop new component its the same error.
![image](https://user-images.githubusercontent.com/41608759/166117269-598fa7da-ecb5-4119-9d5f-bcab11db6cfd.png)

**Comment by zoedesimone** [comment]
Hi, thanks for posting the screenshot. I know what the error is - will get back to you as soon as this is fixed. Thank you.

**Comment by asisnatha** [comment]
Hi @zoedesimone. Any update on the fix?

**Comment by zoedesimone** [comment]
Hi @asisnatha, 
I am currently out but will be able to fix this bug late next week. I'll send you an update when this is fixed. Thank you for your patience. 
Best regards,
Zoe

**Comment by asisnatha** [comment]
Hi @zoedesimone sorry to disturb you again, do we have  any news on the updated component

**Comment by asisnatha** [comment]
Any update to the copmonent @zoedesimone ?

**Comment by asisnatha** [comment]
hi @kastnerp. Do we have any update on this component.

**Comment by asisnatha** [comment]
Hello all, Its quite a long time. Just wanted to be sure if is there any development on this issue? As beta version is out for quite sometime, when can we expect the new completed version!

**Comment by andydogbo** [comment]
hi 
is there any developpement about this issue @kastnerp  @zoedesimone

**Comment by kastnerp** [comment]
Yes, this should be fixed in `v0.4.1.4`.

**Comment by asisnatha** [comment]
Thank you @kastnerp for the updated module. I will try and recert back if any issue. One thing to get clearified, will this version support rhino8?
