### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by Zeddddd** [EnvironmentalSystemsLab/Eddy3D-Public#10]
I can't Download it on Food4forrhino showed some random letters nor the official website(no link was sent).
![image](https://github.com/EnvironmentalSystemsLab/Eddy3D-Public/assets/37978030/55ac724b-3350-412f-92d3-0a4ac6c70e8c)
![image](https://github.com/EnvironmentalSystemsLab/Eddy3D-Public/assets/37978030/26c5ae03-f467-47ec-b4f6-a57613a07356)

**Comment by kastnerp** [comment]
The issue on Food4Rhino is almost certainly a case of not using “right click” - “save as”. 
The form on the website does not work with Chrome autofill, please input your data manually. 

Best,

Patrick
