### ISSUE TITLE
Missing "polyMesh" Folder when using Cylindrical Domain

### ISSUE THREAD

**Issue by sperrault** [EnvironmentalSystemsLab/Eddy3D-Public#12]
I updated to version 0.4.8.0 and encountered an issue when running RunMsh with Cylindrical Domain (DomainCyl):

```
--> FOAM FATAL ERROR:
Cannot find file "points" in directory "polyMesh" in times "constant" down to constant

    From function virtual Foam::IOobject Foam::fileOperation::findInstance(const Foam::IOobject&, Foam::scalar, const Foam::word&) const
    in file global/fileOperations/fileOperation/fileOperation.C at line 871.

FOAM exiting

```

It appears that the "mesh\constant\polyMesh" folder is not being created by blockMesh and, as a result, is not duplicated in the case folders.

**Comment by kastnerp** [comment]
@sperrault Could you please post your GH file here so I can fix this?

**Comment by kastnerp** [comment]
@sperrault I have just tested the template and everything works fine on my end. Would you be able to upload your case for me to take a look?
[4_AnnualWindAnalysis-R8-0.4.8.0.gh.zip](https://github.com/user-attachments/files/16395564/4_AnnualWindAnalysis-R8-0.4.8.0.gh.zip)

**Comment by kastnerp** [comment]
@sperrault I would need the GH file to debug, the case itself won't help me.

**Comment by kastnerp** [comment]
We would need to jump on a call to take a closer look, the template I shared works fine for me. Please reach out to me via email.
