### ISSUE TITLE
Eddy Beta version not working in Grasshopper.

### ISSUE THREAD

**Issue by Somesh-T** [EnvironmentalSystemsLab/Eddy3D-Public#3]
I downloaded the the 0.4.0.10 version of Eddy, I can’t seem to have it working in GH. I have tried Uninstalling and Installing 3 times at this point.

![image](https://user-images.githubusercontent.com/70723572/166933196-84e9dec2-8b99-4268-8270-bfe8a425c6aa.png)

I don’t see any Unblock option on that file, I even checked before installing that the Installer itself is unblocked.

![image](https://user-images.githubusercontent.com/70723572/166933311-41be0b65-d6c8-4706-a901-3730e4b77dde.png)

When i pasted the GH file in “Component folder” i am getting this error.

![image](https://user-images.githubusercontent.com/70723572/166933405-ac20ff4e-8b5c-4418-8061-0c1d0c9c5d48.png)

I also tried the new patch 4.1.1....still same thing. I got Blue CFD 2020 installed too like it was recommended.
I can't get it to work so i have uninstalled the Beta version & CFD 2020. I went back to the stable version and it works just fine...

Let me know what i might be doing wrong here. Thanks!

**Comment by kastnerp** [comment]
@Somesh-T Not sure what is going on here. If you decide to copy the files manually you need to copy both `Eddy.gha` and `EddyLib.dll`. Could you see if this helps?

Best,

Patrick

**Comment by Somesh-T** [comment]
Ok, I'll try that this week and let you know. Thanks!

**Comment by Somesh-T** [comment]
@kastnerp  Normal installation still didn't work for me so i had to manually to copy both "Eddy.gha" and "EddyLib.dll". I am now seeing the Eddy tab in GH and ran a small test & everything checks out. Thanks!
