### ISSUE TITLE
Export Annual Wind Velocities and Wind Factors to CSV file without deconstructing the Results Obj

### ISSUE THREAD

**Issue by monsieurpablo** [EnvironmentalSystemsLab/Eddy3D-Public#4]
Would it be possible to export the Wind Factors, and Wind Annual Velocities to CSV files without deconstructing the results into Grasshopper? This would greatly improve the performance of the plugin in case one wants to use these results in other analyses.

**Comment by kastnerp** [comment]
Sure! You mind explaining what your ideal workflow would be like step by step?

**Comment by monsieurpablo** [comment]
Sure!

I am trying to use the Eddy3D results inside an outdoor comfort calculation. For the UTCI calculation I am using LB tools, and recently they i[mplemented the possibility] (https://discourse.ladybug.tools/t/utci-accounting-for-both-external-glazing-and-point-by-point-wind-speeds/17600/14) to import a `csv` file with the annual velocities for each of the analysis point. In the same post in the LB discourse, they show a workflow to export the results from Eddy to a file, but one must deconstruct and read all the results into GH. It would be great to export the point location and the Annual Wind Velocities into a csv.

**Comment by kastnerp** [comment]
Those files used to be `.csv` but we decided to write everything in binary because ascii is just way too slow.
I don't understand how you would want to use this without any Grasshopper given that the probing point are provided by Grasshopper? In other words, why don't you just export the output of the `DeData` component? If I add the csv export again, it will be at least as slow as the `DeData` component.

**Comment by kastnerp** [comment]
@monsieurpablo This should help you get started: https://github.com/kastnerp/Eddy3D-Helperfunctions/blob/main/read_bins.ipynb

Let me know if you have any questions.

Best,

Patrick

**Comment by monsieurpablo** [comment]
@kastnerp This is really helpful! Thanks you for this. I think it's fine if we don't have a csv file, but instead we have a more efficient `binary` data. Did not know that it was possible to read back the data from Python. This is exactly what I was looking for. 

Would keep you in touch if I get anything meaningful from exporting and visualizing data from Eddy into a Streamlit dashboard, thanks.
