### ISSUE TITLE
Annual Wind Velocities calculation method

### ISSUE THREAD

**Issue by monsieurpablo** [EnvironmentalSystemsLab/Eddy3D-Public#5]
Hi everyone,

I would want you to help me clarify the Wind Factors calculation, because I am getting different results from my python workflow than from Eddy3D.

To my understanding, the Wind Factors are calculated by:

- Dividing the `wind velocity` at the comfort point by the **scaled** (see formula below) `inlet velocity`. This would return a matrix of size (wind_dir, analysis_pts).
- From the weather file get the `wind direction` at every hour, and approximate to match simulated directions. Eg. turn 42 deg to 45 deg. (No interpolation in this case)
- Having the `wind dir adjusted`, look up for the correct wind factors for that direction, and multiply the factors by the **scaled (?)** EPW wind speed at the same height of the comfort point, and repeat for each point at each hour of the year. This would return with a matrix of size (8760 * analysis pts).

Is this process correct? I am getting different results from Eddy than from Python or native GH components. 

In another question, I am using the following formula for the Logarithmic wind profile, is this right?

```python
def scaleWind (Uinit, Zinit = 10, Zend = 1.5,  z0 = 1.0, d = 0):
    if Zend > z0: Uend = (Uinit * ((math.log(Zend - d /z0) / (math.log(Zinit - d /z0)))))
    else: Uend = 0
    return Uend
```

**Comment by kastnerp** [comment]
Calculation method is explained [here](https://www.researchgate.net/publication/346039200_Predicting_space_usage_by_multi-objective_assessment_of_outdoor_thermal_comfort_around_a_university_campus).
