### ISSUE TITLE
Wind exposures per orientation

### ISSUE THREAD

**Issue by JulioAmodia1989** [EnvironmentalSystemsLab/Eddy3D-Public#8]
Hi there,

I was wondering if would be possible to incorporate this feature into the new EDDY3D release.
Thanks

**Comment by kastnerp** [comment]
Would you mind elaborating?

**Comment by JulioAmodia1989** [comment]
Hi Kastnerp,
I found in some urban contexts, especially in the periphery the wind exposure varies depending on the orientation. That is, if the urban areas located to the west, the wind exposure in that orientation will be lower than the east (i.e. in a coastal region where the sea is on the east side). 
This can affect considerably the annual wind results, where several wind orientations are studied.
I hope I made myself understood.
Thanks

**Comment by kastnerp** [comment]
This had been implemented in `v0.4.2.0`.
